# Generated by Django 4.2.1 on 2023-05-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circuito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('alcance', models.CharField(max_length=64)),
                ('ranking_premios', models.IntegerField()),
                ('cant_torneos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('nacionalidad', models.CharField(max_length=64)),
                ('edad', models.DateField()),
                ('circuito', models.CharField(max_length=64)),
                ('marca', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('origen', models.CharField(max_length=64)),
            ],
        ),
    ]
