# Generated by Django 4.2.1 on 2023-05-23 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PadelApp', '0004_comentario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='objeto_id',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='objeto_type',
        ),
    ]
